### ISSUE TITLE
I get some troubles when running net...

### ISSUE THREAD

**Issue by PolarisD** [matansel/pix2vertex#10]
I use GPU and change the  run_net.lua file :
output = model:cuda():forward(in_im:cuda()):double()
but I still got errors:

Running Net.../**/torch/install/bin/luajit: /**/torch/install/share/lua/5.1/torch/Tensor.lua:238: attempt to index a nil value
stack traceback:
	/**/torch/install/share/lua/5.1/torch/Tensor.lua:238: in function 'type'
	.**/torch/install/share/lua/5.1/nngraph/gmodule.lua:233: in function 'recursiveType'
	**/torch/install/share/lua/5.1/nngraph/gmodule.lua:247: in function 'applyTypeToTable'
	**/torch/install/share/lua/5.1/nngraph/gmodule.lua:252: in function 'cuda'
	run_net.lua:27: in main chunk
	[C]: in function 'dofile'
	**/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Error using load
Unable to read file '/**/pix2vertex-master/imgs/2327-3-res.mat'. No such file or directory.

Error in run_net (line 13)
net_res = load(resname);

Error in runme (line 26)
im_pncc = run_net( img, '/**/pix2vertex-master/models/pncc_net.t7', im_file(1:end-4));

Do you know how to fix it?

**Comment by wenpanli** [comment]
Hey, how did you solve this problem?Can you please share?

**Comment by PolarisD** [comment]
Sorry I forgot it. 
But I have checked my run_net.lua  file and found that I didn't modify it. Maybe you can have a try.

**Comment by PolarisD** [comment]
@SampanLee
Sorry I forgot it. 
But I have checked my run_net.lua  file and found that I didn't modify it. Maybe you can have a try.

**Comment by wenpanli** [comment]
Thanks for your reply, I will try.

**Comment by Ankitdulani** [comment]
@SampanLee 
Did you found how to resolve this problem.

**Comment by wenpanli** [comment]
I am sorry I have not solved this problem up to now. If there is a solution, I will share it here.

**Comment by Ankitdulani** [comment]
@SampanLee 
Hey I'm running this implementation on VM. And just found out the error was my RAM wasn't suffcient to load the models. So When I had upgrade the RAM size allocated to VM the code works just fine.
