### ISSUE TITLE
How can I generate the training data?

### ISSUE THREAD

**Issue by xiaoxingzeng** [matansel/pix2vertex#12]

**Comment by xiaoxingzeng** [comment]
Hi Matan:
    When I want projecte the 3d face of 3dmm on image plane, I got the projection like this:
    
![1 2](https://user-images.githubusercontent.com/22523429/48907042-518adb00-eea1-11e8-9ce2-bb6e8536db01.png)
How did you got the perfect projected image? thanks very much

**Comment by Ivy147** [comment]
hi，I want to know how to generate the training data,too?And how to choose backgrounds?
