### ISSUE TITLE
Problem about 'postprocess.p' output

### ISSUE THREAD

**Issue by Fanziapril** [matansel/pix2vertex#2]
The code could run successfully, but the output is random. The output of the deep network is good but when doing 'Affine Align', the alignment results between the depth and 3D template are random. The results are different when running the code several times. Sometimes only partial face is reconstructed. I think this may be the depth cannot align well with the template. The 'postprocess.p' is protected so I cannot figure out the problem.

**Comment by matansel** [comment]
OK. Can you please share the image?

**Comment by Fanziapril** [comment]
When I run for the first time, the output of the deep network is:
![1-1](https://user-images.githubusercontent.com/21120421/29546635-242e2428-8728-11e7-96e5-b3ae4ae88862.jpg)

![1-2](https://user-images.githubusercontent.com/21120421/29546641-292b74bc-8728-11e7-8d0c-0182191501e5.jpg)

This is good. And During the postprocess function:
![screenshot from 2017-08-22 10 30 47](https://user-images.githubusercontent.com/21120421/29546516-7cc7633e-8727-11e7-8201-20975e855ee3.png)
This is a good alignment.
![screenshot from 2017-08-22 10 31 05](https://user-images.githubusercontent.com/21120421/29546527-8bcb7f96-8727-11e7-81fc-b19b2cf66c38.png)
![screenshot from 2017-08-22 10 33 21](https://user-images.githubusercontent.com/21120421/29546531-913ea2a0-8727-11e7-928c-2275da80a7a5.png)

And the final result is:

![1-3](https://user-images.githubusercontent.com/21120421/29546571-ce82ebd0-8727-11e7-8126-4f2020393d55.jpg)![1-4](https://user-images.githubusercontent.com/21120421/29546572-cff94bda-8727-11e7-867e-e6cda732086b.jpg)

When I run for the second time, the output of the deep network is:
![2-1](https://user-images.githubusercontent.com/21120421/29546672-44d3dd9e-8728-11e7-9531-11bd3e2b7044.jpg)
![2-2](https://user-images.githubusercontent.com/21120421/29546677-475834ca-8728-11e7-8846-eafa6e2b55fb.jpg)
This is slightly different from the first time. 

During the postprocess function:
![screenshot from 2017-08-22 10 35 42](https://user-images.githubusercontent.com/21120421/29546708-760030ca-8728-11e7-9d04-4ffce0920ba8.png)
![screenshot from 2017-08-22 10 36 00](https://user-images.githubusercontent.com/21120421/29546720-8a27fbaa-8728-11e7-9872-7b06e1675b12.png)
![screenshot from 2017-08-22 10 36 39](https://user-images.githubusercontent.com/21120421/29546728-92e9c11a-8728-11e7-9261-2e7c480767b8.png)
![screenshot from 2017-08-22 10 37 47](https://user-images.githubusercontent.com/21120421/29546731-967285a6-8728-11e7-90a6-3a5c43e99874.png)

The liagnment between the depth and template is bad, then the final result is partial:

![2-4](https://user-images.githubusercontent.com/21120421/29546755-afbb7ec8-8728-11e7-9082-3afd489d37f2.jpg)![2-3](https://user-images.githubusercontent.com/21120421/29546757-b1ce4bc8-8728-11e7-8387-fc18e3b2c482.jpg)

I don't know why this happened... I am running the code on the Ubuntu 14.04 LTS.

**Comment by matansel** [comment]
So obviously the result of the network is different than what we've got. Since concolutional layers are not scale invariant, it is important to use the same scale of the face in the input image as in the training images. Did you use the same face cropping we used? Maybe the face detector provides different bounding box than ours. Try to continuously increase the size of your bounding box around the face such that the face will take a smaller portion of the image.

**Comment by matansel** [comment]
The input of the network is inconsistent with the cropping

**Comment by Fanziapril** [comment]
Thanks for your quick reply. I am using the exact same face detector(vision.CascadeObjectDetector and all the property is default) as you are. But I am using MATLAB 2017a,  maybe the face detection algorithms are different between different MATLAB versions.

I manually cropped the bounding box and try to make it looks like the image showed in your paper(Fig 10).
`FaceDetect = vision.CascadeObjectDetector; `
`BB = step(FaceDetect,img);`
`scale = 1.1;`
`BB(1,1) = BB(1,1) - 0.5*(scale-1)*BB(1,3);`
`%BB(1,2) = BB(1,2) - 0.5*(scale-1)*BB(1,4);`
`BB(1,3) = scale*BB(1,3);`
`BB(1,4) = scale*BB(1,4);`
`imsz = size(img);`
This solved the problem. 
However, there is another problem: I directly used the cropped image, but still get different final results.
The cropped image is:
![crop](https://user-images.githubusercontent.com/21120421/29551161-11566146-8744-11e7-875a-b962b578c2fa.png)
first running:
![tmp6](https://user-images.githubusercontent.com/21120421/29551311-b45426c6-8744-11e7-9be6-9581e48f0c3b.jpg)![tmp5](https://user-images.githubusercontent.com/21120421/29551313-b6801202-8744-11e7-9d60-0213b0449899.jpg)

second running:
![tmp7](https://user-images.githubusercontent.com/21120421/29551322-c1478210-8744-11e7-81b4-b5fcc3704c94.jpg)![tmp8](https://user-images.githubusercontent.com/21120421/29551323-c21d64fc-8744-11e7-81b2-1b2a7843f92e.jpg)

I think the bounding box should not be the reason. Is there any possible that the output of deep network or postprocess are different when running the code for several times?

**Comment by matansel** [comment]
Could you please attach the result of the network of the right scale?
The postprocessing step is highly dependent upon the result of the network and usually doesn't fail.

**Comment by Fanziapril** [comment]
Yes. I listed teo different results when I running the code using the same cropped image:
First time:
![run1](https://user-images.githubusercontent.com/21120421/29658162-92b849b2-88ec-11e7-875c-5c1871c8a14b.jpg)
Second time:
![run2](https://user-images.githubusercontent.com/21120421/29658166-96082128-88ec-11e7-89ea-9e25ddc3ea8c.jpg)
(From the output of network, there are small differences in the left cheek)
First time:
![run1-1](https://user-images.githubusercontent.com/21120421/29658192-ab757830-88ec-11e7-93d2-40665d781e66.jpg)
Second time:
![run2-1](https://user-images.githubusercontent.com/21120421/29658203-b2c80cc4-88ec-11e7-8960-152388c04f25.jpg)
First time:
![run1-2](https://user-images.githubusercontent.com/21120421/29658209-ba2aa9ea-88ec-11e7-9758-70fe987495c2.jpg)![run1-3](https://user-images.githubusercontent.com/21120421/29658212-bb479b8a-88ec-11e7-98b0-31c59a3f6a0b.jpg)
Second time:
![run2-2](https://user-images.githubusercontent.com/21120421/29658232-c4782d64-88ec-11e7-9a00-9e6519d2522d.jpg)![run2-3](https://user-images.githubusercontent.com/21120421/29658237-c7ad7098-88ec-11e7-8fbc-8da3755e55b3.jpg)

**Comment by matansel** [comment]
The result of the network is still poor because the scale of the face in the image is different than the paper. Perhaps also the relative position of the face in the image is also set inaccurately. Try to run the face detector of Matlab 2015a if you can.

**Comment by Fanziapril** [comment]
I've tried Matlab2013a, 2014a, 2016a(I didn't find a 2015a in my lab), could you please send me the cropped image so I can find where my problem is?

**Comment by matansel** [comment]
The input image to the networks is the following:
![sample_img](https://user-images.githubusercontent.com/17706107/29822314-d8180088-8c7f-11e7-8868-161d76dcd5c3.png)

And this is these are the outputs you should get:
Correspondence map:
![sample_pncc](https://user-images.githubusercontent.com/17706107/29822349-fda8ebfa-8c7f-11e7-875b-3df3e52325aa.png)

Depth map:
![sample_depth](https://user-images.githubusercontent.com/17706107/29822367-111ef8f0-8c80-11e7-9c35-a5c6883fde3d.png)

The networks are deterministic, so you should get the exact same outputs.

**Comment by PolarisD** [comment]
I use GPU and change the run_net.lua file :
output = model:cuda():forward(in_im:cuda()):double()
but I still got errors:

Running Net...//torch/install/bin/luajit: //torch/install/share/lua/5.1/torch/Tensor.lua:238: attempt to index a nil value
stack traceback:
//torch/install/share/lua/5.1/torch/Tensor.lua:238: in function 'type'
./torch/install/share/lua/5.1/nngraph/gmodule.lua:233: in function 'recursiveType'
**/torch/install/share/lua/5.1/nngraph/gmodule.lua:247: in function 'applyTypeToTable'
**/torch/install/share/lua/5.1/nngraph/gmodule.lua:252: in function 'cuda'
run_net.lua:27: in main chunk
[C]: in function 'dofile'
/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50
Error using load
Unable to read file '//pix2vertex-master/imgs/2327-3-res.mat'. No such file or directory.

Error in run_net (line 13)
net_res = load(resname);

Error in runme (line 26)
im_pncc = run_net( img, '/**/pix2vertex-master/models/pncc_net.t7', im_file(1:end-4));

how can I fix it?
