### ISSUE TITLE
Can I run this code with a GPU?

### ISSUE THREAD

**Issue by happsky** [matansel/pix2vertex#4]
Thanks for sharing this code, however, it's a little bit slow when I running it,  can I running it with a GPU?

**Comment by eladrich** [comment]
Sure, we use the Torch framework which supports both CPU and GPU calculations.
To run our network in GPU mode, modify the `run_net.lua` file accordingly, something like:
`output = model:cuda():forward(in_im:cuda()):double()`
Notice that this will not affect the postprocessing part which is not optimized for GPU.
