### ISSUE TITLE
How to export genreated mesh? And how to leave the mesh unchopped so the vertex order kept? 

### ISSUE THREAD

**Issue by xgits** [matansel/pix2vertex#5]
How to export genreated mesh? Like to obj.
And how to leave the mesh unchopped so the vertex order kept?

**Comment by xgits** [comment]
I know how to generate mesh now, but unchopping is a big problem

**Comment by eladrich** [comment]
See the result of the depth2mesh part of the updated pipeline

**Comment by KangolHsu** [comment]
How to generate mesh ? could you give me some advices? @xgits 
Thank you

**Comment by Sunloggy** [comment]
How to export mesh to stl or obj? pls help me!

**Comment by ZHJNCUT** [comment]
> 如何导出流派网格？喜欢 obj. 以及如何保持网格不被切割从而保持顶点顺序？

Have you solved it yet? I want to learn too

**Comment by ZHJNCUT** [comment]
> 如何将网格导出为 stl 或 obj？请帮助我！

Have you solved it yet? I want to learn too

**Comment by ZHJNCUT** [comment]
> 如何将网格导出为stl或obj？请帮助我！

Have you solved it yet? I want to learn too
