### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by khmariem** [matansel/pix2vertex#6]
Hello,

when compiling the code, I found out that the line **system(['OMP_NUM_THREADS=1 th run_net.lua -model ' net_path ' -inputs ' matname ' -res ' resname ]);** in "run_net.m" doesn't work for me.
When typing this: **[f,k]=system(['OMP_NUM_THREADS=1 th run_net.lua -model ' net_path ' -inputs ' matname ' -res ' resname ])** I get these results:

k =

   127

f =

    '/mnt/appl/software/Torch/1.0-goolfc-2018a/bin/luajit: symbol lookup error: /home.others/eb/easybuild/software/Torch/1.0-goolfc-2018a/lib/libTH.so.0: undefined symbol: dgemm_
     '
Does anyone know how to fix this?

Thanks in adavance.

**Comment by eladrich** [comment]
Looks like a Torch error, unrelated to our code
