### ISSUE TITLE
Separate Non-Rigid Registration and Fine-Details Recon

### ISSUE THREAD

**Issue by tranluan** [matansel/pix2vertex#7]
Hi Matan and Elad,

Thanks for an awesome work!
In your paper Fig.9, you show results of each one of your 3 steps results.
However, in the code, the non-rigid registration and fine-details reconstruction are packed into a single post-processing function. Is it possible that you provide them as two separate functions?

That would be really helpful in many scenarios; i.e if ground truth coarse shape is given, it's can be feed to your refinement module to do further processing.

Thanks

**Comment by eladrich** [comment]
Hi,
Thanks for the compliments :-)

That's a good idea, will do.

**Comment by eladrich** [comment]
Updated repository with separated functions
