### ISSUE TITLE
File model/template.mat is missing

### ISSUE THREAD

**Issue by mathue** [matansel/pix2vertex#8]
The file template.mat is missing in the mentioned Google drive zip file. It is required in the function raw2depth.m.

**Comment by eladrich** [comment]
Oops, uploading an updated .zip.
Meanwhile you can find it in the old one:
https://drive.google.com/open?id=0B1j6t9f_-lyrRGhOSnJyVXhvaEU

**Comment by eladrich** [comment]
Updated link
